version: '3'
services:

  front-envoy:
    build:
      context: ./
      dockerfile: Dockerfile-frontenvoy
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
      - "1234"
      - "9191"
    ports:
      - "80:80"
      - "8001:8001"
      - "1234:1234"
      - "9191:9191"

  service1: &service1
    build:
      context: ./
      dockerfile: Dockerfile-service1
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  service1-1:
    <<: *service1

  service1-2:
    <<: *service1

  service1-3:
    <<: *service1

  service2:
    build:
      context: ./
      dockerfile: Dockerfile-service2
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"
networks:
  envoymesh: {}
